
# AWS CodeBuild buildspec.yml v0.2
version: 0.2

env:
  variables:
    docker_tag: damientstuart/trapex
    ecr_repo: trapex

# ===  Build stages  ======================================
phases:
  install:
    run-as: root
    on-failure: ABORT
    commands:
      - yum -y install golang golang-godoc docker
      - service docker start
      - usermod -a -G docker ec2-user

  pre_build:
    commands:
      - echo "My id is `id`"
      - echo "My MY_AWS_ACCOUNT_ID is $MY_AWS_ACCOUNT_ID"
      - env
      - docker info
      - go get ./...

  build:
    commands:
      - go build ./...
      - docker build -t ${docker_tag} -f tools/docker/Dockerfile .
      - docker images

  post_build:
    commands:
      - export ECR_REGISTRY="https://${MY_AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}
      - docker tag ${docker_tag}:latest ${ECR_REGISTRY}/${ecr_repo}:latest
      - docker push ${ECR_REGISTRY}/${ecr_repo}:latest

