# AWS CloudFormation YAML

Parameters:
  BuildSpec:
    Type: String
    Description: buildspec.yml file location
    Default: tools/aws/buildspec_docker.yml
  CodeBuildImage:
    Type: String
    Description: https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html
    Default: aws/codebuild/amazonlinux2-x86_64-standard:3.0

Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: trapex_docker_image
      Description: Builds trapex Docker image
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !Ref CodeBuildImage
        PrivilegedMode: true
        EnvironmentVariables:
            - Name: MY_AWS_ACCOUNT_ID
              Type: PLAINTEXT
              Value: !Sub ${AWS::AccountId}
      Source:
        Type: GITHUB
        Location: https://github.com/damienstuart/trapex.git
        BuildSpec: !Ref BuildSpec
      Visibility: PUBLIC_READ

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: [sts:AssumeRole]
          Effect: Allow
          Principal:
            Service: [codebuild.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - codebuild:*
                - ec2:CreateNetworkInterface
                - ec2:DescribeNetworkInterfaces
                - ec2:DeleteNetworkInterface
                - ec2:DescribeSubnets
                - ec2:DescribeSecurityGroups
                - ec2:DescribeDhcpOptions
                - ec2:DescribeVpcs
                - ec2:CreateNetworkInterfacePermission
                - logs:*
                Effect: Allow
                Resource: '*'

  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: trapex
      ImageScanningConfiguration: 
        ScanOnPush: true

