
# AWS CodeBuild buildspec.yml v0.2
version: 0.2

# To use the file at this location, must update the CODEBUILD_SRC_DIR

phases:
  install:
    run-as: root
    on-failure: ABORT
    commands:
      - yum -y install golang rpm-buld rpmdevtools glolang-godoc

  pre_build:
    commands:
      - echo "Entered the pre-build phase..."
      - rpmdev-setuptree
      - go get ./...

  build:
    commands:
      - go build ./...

  post_build:
    commands:
      - echo "Entered the post-build phase..."
      - rpmbuild -ba tools/rpm.spec

artifacts:
  files:
    - trapex*.rpm
  name: trapex.rpm
  discard-paths: yes
  base-directory: ~/rpmbuild/RPMS/**/*

cache:
  paths:
    - ~/go/src/**/*

