# AWS CloudFormation YAML

Parameters:
  CodeBuildImage:
    Type: String
    Description: https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html
    Default: aws/codebuild/amazonlinux2-x86_64-standard:3.0

Resources:
  TrapexCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: trapex
      Description: Builds the trapex binary and RPM
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        # Initial testing to see if build will work
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !Ref CodeBuildImage
      Source:
        Type: GITHUB
        Location: https://github.com/damienstuart/trapex.git
        BuildSpec: tools/buildspec.yml
      Visibility: PUBLIC_READ

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [codebuild.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 'logs:*'
                - 'ec2:CreateNetworkInterface'
                - 'ec2:DescribeNetworkInterfaces'
                - 'ec2:DeleteNetworkInterface'
                - 'ec2:DescribeSubnets'
                - 'ec2:DescribeSecurityGroups'
                - 'ec2:DescribeDhcpOptions'
                - 'ec2:DescribeVpcs'
                - 'ec2:CreateNetworkInterfacePermission'
                Effect: Allow
                Resource: '*'

