
FROM public.ecr.aws/docker/library/amazonlinux:latest

EXPOSE 162
EXPOSE 80

RUN yum -y install net-snmp-utils

RUN mkdir -p /opt/trapex/bin /opt/trapex/etc /opt/trapex/log
COPY trapex /opt/trapex/bin
COPY tools/trapex.conf /opt/trapex/etc

# Install root bash history
COPY tools/docker/root_bash_history /root/.bash_history
COPY tools/docker/root_vimrc /root/.vimrc

CMD ["/opt/trapex/bin/trapex", "-c", "/opt/trapex/etc/trapex.conf"]
